---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(leaflet)
library(tidygeocoder)
library(ggridges)

data("rest_inspec")
nycrest =
  rest_inspec %>%
  group_by(camis) %>%
  slice(which.max(as.Date(inspection_date, "%Y-%m-%d", tz = "America/New_York"))) %>%
  filter(boro == "BRONX") %>%
  drop_na(score) %>%
  drop_na(grade) %>%
  filter(critical_flag %in% c("Critical", "Not Critical")) %>%
  filter(grade %in% c("A", "B", "C"))

nycrest2 =
nycrest %>%
    mutate(address = str_c(building, " " , street, " New York, NY", " ", zipcode))

addresses = 
  nycrest2 %>%
  geocode(address = address, method = "census", verbose = TRUE)

addresses2_df =
  addresses %>%
  drop_na(lat) %>%
  mutate(restaurant_name = dba)

cuisinerating =
  rest_inspec %>%
  group_by(camis) %>%
  slice(which.max(as.Date(inspection_date, "%Y-%m-%d", tz = "America/New_York"))) %>%
  filter(boro == "MANHATTAN") %>%
  drop_na(score) %>%
  drop_na(grade) %>%
  filter(cuisine_description != "Not Listed/Not Applicable") %>%
  group_by(cuisine_description) %>%
  summarise(avg_score = round(mean(score),0))

gradeboro =
  rest_inspec %>%
  group_by(camis) %>%
  slice(which.max(as.Date(inspection_date, "%Y-%m-%d", tz = "America/New_York"))) %>%
  filter(grade %in% c("A","B","C")) %>%
  filter(boro != "Missing") %>%
  drop_na(score) %>%
  drop_na(grade) %>%
  group_by(boro) %>%
  count(grade, name = "count_grade")

time =
  rest_inspec %>%
  filter(grade %in% c("A","B","C")) %>%
  filter(boro == "MANHATTAN") %>%
  drop_na(score) %>%
  drop_na(grade) %>%
  filter(dba %in% c("AU BON PAIN")) %>%
  arrange(inspection_date) %>%
  mutate(name = str_c(building, " ", street)) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
pal = colorFactor("viridis", NULL)

restaurants_df %>%
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(~long, ~lat, radius = 1, color = ~pal(grade), popup = ~restaurant_name) %>%
    addLegend("bottomright", pal = pal, values = ~grade,
    title = "Restaurant Grade",
    opacity = 1)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
cuisinerating  %>%
plot_ly(
    x = ~cuisine_description, y = ~avg_score, type = "scatter", mode = "markers",
    color = ~avg_score, alpha = 0.5) %>%
    layout(title = list(text = "Average Most Recent Inspection Score by Cuisine Type in Manhattan", 
                        xanchor = 'center', yanchor =  'top', size = 8),
           yaxis = list(title = list(text = "Average Score")), 
           xaxis = list(title = list(text = "Cuisine Description"), showticklabels = FALSE))
```

### Chart C

```{r}
gradeboro %>% 
  plot_ly(x = ~grade, y = ~count_grade, color = ~boro, type = "bar", colors = "viridis",
          facet_col = "boro") %>%
  layout(title = list(text = "Count of Inspection Grades Received by Borough", 
                        xanchor = 'center', yanchor =  'top', size = 8),
           yaxis = list(title = list(text = "Count")), 
           xaxis = list(title = list(text = "Grade")))
```

### Chart D

```{r}
time  %>%
 plot_ly(
    x = ~inspection_date, y = ~score,
    type = "scatter",color = ~name, mode = "lines+markers", colors = "viridis") %>%
     layout(yaxis = list(title = list(text = "Score Received")), 
           xaxis = list(title = list(text = "Inspection Date")),
           title = list(text = "Inspection Grades Received Over Time Among Manhattan Au Bon Pains", 
                        xanchor = 'center', yanchor =  'top', size = 8))
```
