---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(leaflet)
library(tidygeocoder)
library(ggridges)
```

Filtering NYC restaurant data to include only restaurants in Bronx and only inspections that are the most recent for a particular restaurant. 
```{r}
data("rest_inspec")
nycrest =
  rest_inspec %>%
  group_by(camis) %>%
  slice(which.max(as.Date(inspection_date, "%Y-%m-%d", tz = "America/New_York"))) %>%
  filter(boro == "BRONX") %>%
  drop_na(score) %>%
  drop_na(grade) %>%
  filter(critical_flag %in% c("Critical", "Not Critical")) %>%
  filter(grade %in% c("A", "B", "C"))
```

```{r, eval=FALSE}
restaurants_df = read_csv("geocodedfile.csv")

pal = colorFactor("viridis", NULL)

restaurants_df %>%
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(~long, ~lat, radius = 1, color = ~pal(grade), popup = ~restaurant_name) %>%
    addLegend("bottomright", pal = pal, values = ~grade,
    title = "Restaurant Grade",
    opacity = 1)
  
```

Filtering dataset to include only most recent inspection date and restaurants only in Manhattan. 
```{r}
data("rest_inspec")

unique(pull(rest_inspec, violation_code))

cuisinerating =
  rest_inspec %>%
  group_by(camis) %>%
  slice(which.max(as.Date(inspection_date, "%Y-%m-%d", tz = "America/New_York"))) %>%
  filter(boro == "MANHATTAN") %>%
  drop_na(score) %>%
  drop_na(grade) %>%
  filter(cuisine_description != "Not Listed/Not Applicable") %>%
  group_by(cuisine_description) %>%
  summarise(avg_score = round(mean(score),0))
```

## Make a scatterplot

Here's a plotly scatterplot

```{r}
cuisinerating  %>%
plot_ly(
    x = ~cuisine_description, y = ~avg_score, type = "scatter", mode = "markers",
    color = ~avg_score, alpha = 0.5) %>%
    layout(title = list(text = "Average Most Recent Inspection Score by Cuisine Type in Manhattan", 
                        xanchor = 'center', yanchor =  'top', size = 8),
           yaxis = list(title = list(text = "Average Score")), 
           xaxis = list(title = list(text = "Cuisine Description"), showticklabels = FALSE))
```

```{r}
gradeboro =
  rest_inspec %>%
  group_by(camis) %>%
  slice(which.max(as.Date(inspection_date, "%Y-%m-%d", tz = "America/New_York"))) %>%
  filter(grade %in% c("A","B","C")) %>%
  drop_na(score) %>%
  drop_na(grade) %>%
  group_by(boro) %>%
  count(grade, name = "count_grade")
```


## Barplot 

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```
